# Generated by Django 5.2.7 on 2025-10-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='description',
        ),
    ]
