# Generated by Django 5.2.7 on 2025-10-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('payment', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mpesa', 'M-Pesa')], default='cash', max_length=20)),
                ('card_nnumber', models.CharField(blank=True, max_length=30)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=10, null=True)),
                ('card_cvc', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
