# Generated by Django 5.2.7 on 2025-10-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='card_nnumber',
            new_name='card_number',
        ),
    ]
