# Generated by Django 5.2.7 on 2025-10-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_card_nnumber_reservation_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
