# Generated by Django 5.2.7 on 2025-10-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_reservation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='expiry_date',
            new_name='expiry',
        ),
    ]
