# Generated by Django 5.2.7 on 2025-10-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_expiry_date_reservation_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='expiry',
            new_name='expiry_date',
        ),
    ]
